### ISSUE TITLE
userspace only driver (libusb)

### ISSUE THREAD

**Issue by jclaisse** [lambdaconcept/ft60x_driver#3]
Hi,

First of all, thank you for sharing this work.  

We have some issue regarding the proprietary driver with permissions on Android. So you are exploring the possibility to rewrite or use on open source driver.  

Why did you write it at kernel level? Can a simple userspace library (based on generic kernel driver, ie libusb) do the job?

Regards

**Comment by povauboin** [comment]
Hello,

There is a libusb implementation here:
https://github.com/ufrisk/LeechCore-plugins/tree/master/leechcore_ft601_driver_linux

**Comment by jclaisse** [comment]
Really nice !  

Thank you
